name: markdownlint
on:
  pull_request:
    branches:
      - "main"

    paths:
      - "**/*.md"

  workflow_dispatch:
    inputs:
      paths:
        default: "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: |
            *.md
            !test/*.md
